config/routes.rb
SampleApp::Application.routes.draw do
  get "searches/index"

  get "relationships/create"

  get "relationships/destroy"

  resources :searches
  resources :sessions, :only=>[:new ,:create ,:destroy]
  resources :microposts, :only=>[:create, :destroy]
  resources :relationships, :only=>[:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end

  get "microposts/create"

  get "microposts/destroy"

  match '/signup'=>'users#new'

  match '/signin'=> 'sessions#new'

  match '/signout'=>'sessions#destroy'

  match '/about' =>'pages#about'

  match '/contact' =>'pages#contact'

  match '/help' =>'pages#help'

  root :to=>'pages#home'

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_filter :authenticate
  def index
    redirect_to(root_path) and return if params[:q].nil?

    query = params[:q].strip.inspect
    model = params[:model]
    page  = params[:page] || 1

    unless %(User Page).include?(model)
      flash[:error]="Invalid search!"
      redirect_to(root_path) and return
    end

    if query.blank?
      @results = []
    else
      if model == "User"
        #@results = User.search(query).paginate(:page => page)
        @results = User.search query, :page => page
      else
        @results = Micropost.search query, :page => page,
                                           :conditions => {:created_at => 1.month.ago.to_i..Time.now.to_i}
        #@results = Micropost.search(query, :conditions => {:created_at => 1.month.ago.to_i..Time.now.to_i}).paginate(:page => page)
      end
    end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper

  # Return the model to be searched based on params.
  def search_model
    return "User"    if params[:controller] =~ /users/
    return "Message" if params[:controller] =~ /home/
    params[:model] || params[:controller].classify
  end

  def search_type
    if params[:controller] == "pages" or params[:model] == "Page"
      "microposts"
    else
      "users"
    end
  end

  # Return the partial (including path) for the given object.
  # partial can also accept an array of objects (of the same type).
  def partial(object)
    object = object.first
    klass = object.class.to_s
    dir = "searches"
    if klass == "User"
      #dir  = "users"
      part = "user"
    else
      #dir  = 'shared'
      part = "micropost"
    end
    return "#{dir}/#{part}"
  end
end

app/views/searches/_box.html.erb
<h4>Search <%= search_type %> </h4>
<% form_tag searches_path, :method => :get, :id => "frmSearch" do %>
  <fieldset title="Search">
    <%= text_field_tag :q, h(params[:q]), :id => "txtSearch", :class => "txt",
                                          :maxlength => 50 %>
    <%= submit_tag "Search", :name => nil, :id => "btnSearch",
                             :class => "button"  %>
    <%= hidden_field_tag "model", search_model %>
  </fieldset>
<% end %>

app/views/searches/_micropost.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(micropost.user), micropost.user %>
  </td>
  <td class="micropost">
    <span class="user">
      <%= link_to micropost.user.name, micropost.user %>
    </span>
    <span class="content"><%= wrap(micropost.excerpts.content) %></span></br>
    <span class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago
    </span>
  </td>
  <% if current_user?(micropost.user) %>
  <td>
    <%= link_to "delete", micropost, :method=>:delete,
                :confirm=>"You sure?", :title=>micropost %>
  </td>
  <% end %>
</tr>

app/views/searches/_user.html.erb
<li>
  <%= gravatar_for user, :size=>40 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
  |  <%= link_to "delete", user, :method=>:delete,
                 :confirm=>"You sure?", :title=>"Delete #{user.name}" %>
  <% end %>
</li>

app/views/searches/index.html.erb
<h2>Search results</h2>
  <%= will_paginate(@results) %>
    <% if @results.empty? %>
      <h3>No results</h3>
    <% else %>
    <table><span class=“match”>

        <td>
          <ul class= <% search_type %> >

            <%= render :partial => partial(@results), :collection => @results %>

          <ul>
        </td></span>

     </table>
    <% end %>
  <%= will_paginate(@results) %>